Add basic menu for including our tools.
gbMichelle/Blendkrieg pull request #13
Opened 2019-08-15 22:59 UTC by gbMichelle

Added a basic Krieg button that appears at the top of the window.

Contains:
 - (currently empty) import and export sub menus.
 - A 'Manual' button which links to the wiki for this git.
 - A 'GitHub' button which links to this repository.

Preview:
![img]

[img]: https://i.imgur.com/eLqF0vG.png

2019-08-15 23:02 UTC, gbMichelle commented
Closes #1 
Also updates/corrects the addon metadata.

2019-08-15 23:47 UTC, Mimickal requested changes

2019-08-15 23:47 UTC, Mimickal commented on menu/topbar_dropdown.py
> +    for cls in reversed(classes):
Why do we reverse here? Can we add a short comment with that rationale?

2019-08-15 23:47 UTC, Mimickal commented on menu/topbar_dropdown.py
> +    from bpy.utils import register_class
Let's move these imports to the top of the file to avoid duplication.

2019-08-15 23:47 UTC, Mimickal commented on __init__.py
> +from .menu import topbar_dropdown
What does the dot do here?

2019-08-15 23:47 UTC, Mimickal commented on menu/topbar_dropdown.py
> +# When appended to another menu class
This comment duplicates the info in the below docstring

2019-08-16 00:51 UTC, Mimickal approved these changes

2019-08-16 00:51 UTC, merged